### ISSUE TITLE
Lot's of personal data Opened

### ISSUE THREAD

**Issue by shreyasbapat** [Tushar-Tyagi/IITMandiScraper#1]
Make sure to delete every history of this file from here xD: https://github.com/Tushar-Tyagi/IITMandiScraper/blob/master/btech2017.csv 

That's a lot of personal data you are giving out for free.

**Comment by shreyasbapat** [comment]
Steps: 

```
$ cd IITMandiScraper

$ rm -rf .git/

$ rm btech2017.csv

$ git init

$ git remote add origin  https://github.com/Tushar-Tyagi/IITMandiScraper.git

$ git add .

$ git commit -m "Add Scraper with privacy"

$ git push origin master

```

And you are done :tada:

**Comment by Tushar-Tyagi** [comment]
Thanks! :100:
